-- Famy MDRRMO DRRM Multi-Module Database Schema (Neon PostgreSQL)
CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ir_number TEXT UNIQUE NOT NULL,
    date_time TEXT NOT NULL,
    nature TEXT NOT NULL,
    place TEXT NOT NULL,
    landmark TEXT,
    severity TEXT NOT NULL,
    gis_coordinates JSONB,
    patients JSONB,
    photos JSONB,
    responders JSONB,
    command_personnel JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS system_master_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL, -- 'responder', 'operator', 'incident_type', 'hospital'
    item_value TEXT NOT NULL
);